import { Radiobox } from "./Radiobox";

export function CityOptions({ setCityOption }: any) {
  return (
    <form
      className="city-options"
      onSubmit={(e) => {
        e.preventDefault();
        // @ts-ignore
        setCityOption(e.target.city.value);
      }}
    >
      <Radiobox
        type="radio"
        title="Berlin"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Stuttgart"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Tübingen"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Ulm"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Nuremberg"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Ebersberg"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Markdorf"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Hamburg"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Munich"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="Frankfurt"
        name="city"
        setCityOption={setCityOption}
      />
      <Radiobox
        type="radio"
        title="All"
        name="city"
        setCityOption={setCityOption}
      />
    </form>
  );
}
